# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake3

# The command to remove a file.
RM = /usr/bin/cmake3 -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/csmajs/jgaff001/lab-07-abstract-factory-pattern-lab_07_justin_and_vivian

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/csmajs/jgaff001/lab-07-abstract-factory-pattern-lab_07_justin_and_vivian

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake3 -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake3 -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake3 -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake3 -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/jgaff001/lab-07-abstract-factory-pattern-lab_07_justin_and_vivian/CMakeFiles /home/csmajs/jgaff001/lab-07-abstract-factory-pattern-lab_07_justin_and_vivian/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/csmajs/jgaff001/lab-07-abstract-factory-pattern-lab_07_justin_and_vivian/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f googletest/googlemock/CMakeFiles/gmock_main.dir/build.make googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f googletest/googlemock/CMakeFiles/gmock.dir/build.make googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f googletest/googletest/CMakeFiles/gtest_main.dir/build.make googletest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f googletest/googletest/CMakeFiles/gtest.dir/build.make googletest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

Add.o: Add.cpp.o

.PHONY : Add.o

# target to build an object file
Add.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Add.cpp.o
.PHONY : Add.cpp.o

Add.i: Add.cpp.i

.PHONY : Add.i

# target to preprocess a source file
Add.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Add.cpp.i
.PHONY : Add.cpp.i

Add.s: Add.cpp.s

.PHONY : Add.s

# target to generate assembly for a file
Add.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Add.cpp.s
.PHONY : Add.cpp.s

Div.o: Div.cpp.o

.PHONY : Div.o

# target to build an object file
Div.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Div.cpp.o
.PHONY : Div.cpp.o

Div.i: Div.cpp.i

.PHONY : Div.i

# target to preprocess a source file
Div.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Div.cpp.i
.PHONY : Div.cpp.i

Div.s: Div.cpp.s

.PHONY : Div.s

# target to generate assembly for a file
Div.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Div.cpp.s
.PHONY : Div.cpp.s

Mult.o: Mult.cpp.o

.PHONY : Mult.o

# target to build an object file
Mult.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Mult.cpp.o
.PHONY : Mult.cpp.o

Mult.i: Mult.cpp.i

.PHONY : Mult.i

# target to preprocess a source file
Mult.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Mult.cpp.i
.PHONY : Mult.cpp.i

Mult.s: Mult.cpp.s

.PHONY : Mult.s

# target to generate assembly for a file
Mult.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Mult.cpp.s
.PHONY : Mult.cpp.s

Op.o: Op.cpp.o

.PHONY : Op.o

# target to build an object file
Op.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Op.cpp.o
.PHONY : Op.cpp.o

Op.i: Op.cpp.i

.PHONY : Op.i

# target to preprocess a source file
Op.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Op.cpp.i
.PHONY : Op.cpp.i

Op.s: Op.cpp.s

.PHONY : Op.s

# target to generate assembly for a file
Op.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Op.cpp.s
.PHONY : Op.cpp.s

Pow.o: Pow.cpp.o

.PHONY : Pow.o

# target to build an object file
Pow.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Pow.cpp.o
.PHONY : Pow.cpp.o

Pow.i: Pow.cpp.i

.PHONY : Pow.i

# target to preprocess a source file
Pow.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Pow.cpp.i
.PHONY : Pow.cpp.i

Pow.s: Pow.cpp.s

.PHONY : Pow.s

# target to generate assembly for a file
Pow.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Pow.cpp.s
.PHONY : Pow.cpp.s

Rand.o: Rand.cpp.o

.PHONY : Rand.o

# target to build an object file
Rand.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Rand.cpp.o
.PHONY : Rand.cpp.o

Rand.i: Rand.cpp.i

.PHONY : Rand.i

# target to preprocess a source file
Rand.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Rand.cpp.i
.PHONY : Rand.cpp.i

Rand.s: Rand.cpp.s

.PHONY : Rand.s

# target to generate assembly for a file
Rand.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Rand.cpp.s
.PHONY : Rand.cpp.s

Sub.o: Sub.cpp.o

.PHONY : Sub.o

# target to build an object file
Sub.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Sub.cpp.o
.PHONY : Sub.cpp.o

Sub.i: Sub.cpp.i

.PHONY : Sub.i

# target to preprocess a source file
Sub.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Sub.cpp.i
.PHONY : Sub.cpp.i

Sub.s: Sub.cpp.s

.PHONY : Sub.s

# target to generate assembly for a file
Sub.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/Sub.cpp.s
.PHONY : Sub.cpp.s

unit_test.o: unit_test.cpp.o

.PHONY : unit_test.o

# target to build an object file
unit_test.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/unit_test.cpp.o
.PHONY : unit_test.cpp.o

unit_test.i: unit_test.cpp.i

.PHONY : unit_test.i

# target to preprocess a source file
unit_test.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/unit_test.cpp.i
.PHONY : unit_test.cpp.i

unit_test.s: unit_test.cpp.s

.PHONY : unit_test.s

# target to generate assembly for a file
unit_test.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/unit_test.cpp.s
.PHONY : unit_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... Add.o"
	@echo "... Add.i"
	@echo "... Add.s"
	@echo "... Div.o"
	@echo "... Div.i"
	@echo "... Div.s"
	@echo "... Mult.o"
	@echo "... Mult.i"
	@echo "... Mult.s"
	@echo "... Op.o"
	@echo "... Op.i"
	@echo "... Op.s"
	@echo "... Pow.o"
	@echo "... Pow.i"
	@echo "... Pow.s"
	@echo "... Rand.o"
	@echo "... Rand.i"
	@echo "... Rand.s"
	@echo "... Sub.o"
	@echo "... Sub.i"
	@echo "... Sub.s"
	@echo "... unit_test.o"
	@echo "... unit_test.i"
	@echo "... unit_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

